application: yourdinnerdeals
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /images
  static_dir: images
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /search/request
  script: requestreg.app
  login: admin
- url: /search/.*
  script: search.app
  login: admin
- url: /admin/.*
  script: restaurantadmin.app
  login: admin
- url: /update/restaurantcom
  script: restaurantcom.app
  login: admin
- url: /email/.*
  script: couponemail.app
  login: admin
- url: /.*
  script: main.app

libraries:
- name: django
  version: "1.2"
- name: webapp2
  version: "2.5.2"
- name: lxml
  version: "latest"