application: yourdinnerdeals
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /images
  static_dir: images
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /.*
  script: main.py